package:
  name: reportengine
  version: "{{ GIT_DESCRIBE_TAG[1:] }}.{{ GIT_DESCRIBE_NUMBER }}"

source:
    git_url: ../

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - jinja2
    - pyyaml
    - matplotlib
    - pandas
    - pygments
    - blessings
    - curio
    - pandoc

test:
    requires:
        - pytest
        - hypothesis

    commands:
        - py.test --pyargs reportengine


about:
  home: https://github.com/NNPDF/reportengine
  license: GPL
  summary: 'A general purpose report generator'

