name: Reportengine tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: test
        use-mamba: true
        python-version: ${{ matrix.python-version }}

    - name: Build reportengine package and install it
      shell: bash -l {0}
      run: |
        conda-build conda-recipe/meta.yaml
        conda install --use-local reportengine

    - name: 
    - name: Install pytest dependencies
      shell: bash -l {0}
      run: |
        pip install pytest
        pip install hypothesis

    - name: Run Tests
      shell: bash -l {0}
      run: |
        pytest

